### ISSUE TITLE
KeyError: 'st_features_2d'

### ISSUE THREAD

**Issue by Dhagash4** [hailanyi/CasA#2]
In batch_dict there is no key such as st_features_2d. Can you explain briefly what are the does this key means?

**Comment by hailanyi** [comment]
Was this problem encountered while trying to add our module to OpenPCDet?
Since this repo is modified from my other project, some parts are different from OpenPCDet. The 'st_features_2d' means the 2D features from 2D backbone. It denoted as 'spatial_features_2d' in the original OpenPCDet.

**Comment by Dhagash4** [comment]
Yes, it was encountered while trying to add your module to OpenPCDet, thanks a lot for the reply and open sourcing this project. Also can you please tell ideal way of installation of this project might be beneficial to others.

**Comment by hailanyi** [comment]
Ok, I updated the codes to support Spconv2.X and updated the detailed  installation instructions. This repo is now easier to use.

**Comment by Dhagash4** [comment]
Thanks you so much for making installation easy and now I have CaSA up and running. However I am using custom dataset and the data is quite sparse. Keeping the config of CaSA PV the same I am trying to run that on my dataset, and it is giving me following error. Can you possibly give me directions or hyperparameters that I need to tweak in order to get the network training started.

`RuntimeError: Given groups=1, weight of size [64, 256, 3, 3], expected input[2, 128, 102, 102] to have 256 channels, but got 128 channels instead`

Thanks a lot!

**Comment by hailanyi** [comment]
This may be caused by the inconsistent number of feature channels between 3D backbone and 2D backbone. 
You may use different config compared with CasA. The feature channels of 2D backbone is determined by Point Cloud Range, Voxel Size and 3D Backbone features Channels. Please check that your config is the same as the default config.
[tools/cfgs/dataset_configs/kitti_dataset.yaml](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/dataset_configs/kitti_dataset.yaml)
```
POINT_CLOUD_RANGE: [0, -40, -3, 70.4, 40, 1]
```
[tools/cfgs/kitti_models/CasA-V.yaml](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml)
```
        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.05, 0.05, 0.05]  
    BACKBONE_3D:
        NAME: VoxelBackBone8x
        NUM_FILTERS: [16, 32, 64, 64]
        RETURN_NUM_FEATURES_AS_DICT: True
        OUT_FEATURES: 64

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256
```
```
