### ISSUE TITLE
I can't reach the car moderate precision which I trained for 80 epochs

### ISSUE THREAD

**Issue by Eaton2022** [hailanyi/CasA#4]
I trained the CasA-V for 80 epochs, 3 classes., while I found I can't reach car moderate 3D precision which recall is 11 and by the way ,the other two classes reached the precision as you write in paper. 
I think my batchsize is too small, it's two. I wonder can I use two batchsize to obtain high precision? How to reset learning rate?
Here is the result.
*************** EPOCH 80 EVALUATION *****************
bbox AP:90.7547, 89.7766, 89.5010
bev  AP:90.2147, 88.2992, 88.0006
3d   AP:89.6871, **79.6853**, 79.2249
aos  AP:90.74, 89.67, 89.31
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:96.8148, 95.5741, 93.2506
bev  AP:93.6572, 89.8203, 87.5100
3d   AP:92.9158, **84.1482**, 83.7333

**Comment by hailanyi** [comment]
This may be caused by the high score threshold, you can use lower score threshold (0.7->0.6 or 0.7->0.65) in the [CasA-V.yaml](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/kitti_models/CasA-V.yaml) to test your model.
```
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.6  # tuning the score threshold here to obtain good results 
        OUTPUT_RAW_SCORE: False
```
